### ISSUE TITLE
Quickfix emojis

### ISSUE THREAD

**Issue by BenchBadr** [glassus/terminale_nsi#5]
Bonjour et merci à tous les contributeurs de ce projet, il m'est d'une grande utilité. Outre le fait qu'elle me sert à vous remercier, je souhaite partager une proposition en ce qui concerne l'uilisation des twemojis sur votre site.

<img width="437" alt="image" src="https://github.com/glassus/terminale_nsi/assets/78297845/54af947d-f231-4399-af18-1cc92c059a05">

Ce n'est qu'un détail mais ils ne sont pas vraiment alignés avec le texte.

```css
.emoji {
  display:inline-block; 
  height:1.4em; 
  pointer-events: none;
  width:auto; 
  transform:translate(0, 0.3em);
  -webkit-border-radius: 0;
-moz-border-radius: 0;
border-radius: 0;
}
```

L'ajout de cette classe permet de corriger ce problème

<img width="328" alt="image" src="https://github.com/glassus/terminale_nsi/assets/78297845/e9f30b24-7f3a-48e3-b032-5c954e78d97d">

Je le redis, merci beaucoup pour votre énorme travail de mise en disponibilité au grand public des ressources souvent difficiles à trouver concernant cette spécialité.
